import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
@Component({selector:'pv-about',standalone:true,imports:[RouterLink],template:`
<section class="about-hero"><div class="eyebrow">ABOUT PROCUREVANTA</div><h1>A procurement partner built around <em>clarity.</em></h1><p>ProcureVanta is a Hyderabad-based B2B procurement and sourcing company focused on helping businesses purchase workplace products with less supplier coordination and better commercial visibility.</p><div class="hero-actions"><a class="button dark" routerLink="/contact">Talk to our procurement desk ↗</a><a class="button light" routerLink="/services">View procurement scope</a></div></section>
<section class="story"><div class="story-grid"><div><div class="eyebrow">WHAT WE DO</div><h2>We make business purchasing easier to manage.</h2></div><div><p>Businesses often buy across dozens of categories and suppliers. Our role is to bring structure to that process — understand the requirement, identify sources, compare commercial options and coordinate execution.</p><p>We can support one-off requirements, office setup projects and recurring workplace procurement. The model is intentionally practical: clear requirements, responsive communication and dependable follow-through.</p></div></div></section>
<section class="principles"><div class="eyebrow">OUR APPROACH</div><div class="principle-grid"><article><b>01</b><h3>Requirement first</h3><p>We start with specifications, quantity, timeline and delivery location rather than pushing a fixed catalogue.</p></article><article><b>02</b><h3>Supplier choice</h3><p>We can source across multiple suppliers and present alternatives where the requirement allows it.</p></article><article><b>03</b><h3>Commercial clarity</h3><p>Quotations are organized so stakeholders can compare products, pricing and delivery expectations.</p></article><article><b>04</b><h3>Execution support</h3><p>From order coordination to delivery follow-up, we stay connected through the procurement cycle.</p></article></div></section>
<section class="reach"><div><div class="eyebrow">WHERE WE OPERATE</div><h2>Hyderabad first.<br>India-ready.</h2><p>Our operating base is Hyderabad, Telangana. We can evaluate procurement requirements for businesses with delivery locations across India, subject to category and supplier availability.</p></div><div class="location-card"><span>PRIMARY LOCATION</span><strong>Hyderabad, Telangana, India</strong><small>Corporate procurement · B2B sourcing</small><a href="https://www.google.com/maps/search/?api=1&query=Hyderabad%2C%20Telangana%2C%20India" target="_blank" rel="noopener">Open Hyderabad on Maps ↗</a></div></section>
<section class="about-cta"><div><div class="eyebrow">READY TO START?</div><h2>Have a procurement requirement?</h2></div><a class="button dark" routerLink="/contact">Send an enquiry ↗</a></section>`,styles:[`
.about-hero{padding:105px 8vw 90px;background:linear-gradient(135deg,#f5f8f1,#fbfcf9);border-bottom:1px solid #e5e9e4}.eyebrow{font-size:9px;letter-spacing:.2em;font-weight:800;color:#6c786f;margin-bottom:18px}.about-hero h1{max-width:930px;font:800 clamp(48px,7vw,88px)/.95 Manrope,Arial,sans-serif;letter-spacing:-.065em;margin:0}.about-hero em{font-style:normal;color:#78945a}.about-hero>p{max-width:720px;color:#68736c;font-size:14px;line-height:1.8;margin:28px 0}.hero-actions{display:flex;gap:10px;flex-wrap:wrap}.button{display:inline-flex;align-items:center;border-radius:999px;padding:14px 18px;text-decoration:none;font-size:11px;font-weight:800}.dark{background:#102b24;color:#fff}.light{background:#fff;border:1px solid #dfe5de;color:#26362e}.story{padding:105px 8vw}.story-grid{display:grid;grid-template-columns:1fr 1fr;gap:100px}.story h2,.reach h2,.about-cta h2{font:800 clamp(38px,5vw,60px)/.98 Manrope,Arial,sans-serif;letter-spacing:-.055em;margin:0}.story p,.reach p{font-size:13px;line-height:1.8;color:#6d776f;margin:0 0 20px}.principles{padding:90px 8vw;background:#102b24;color:#fff}.principles>.eyebrow{color:#bcd19b}.principle-grid{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid rgba(255,255,255,.14)}.principle-grid article{padding:28px 25px 0 0;border-right:1px solid rgba(255,255,255,.13);margin-right:25px}.principle-grid article:last-child{border:0;margin:0}.principle-grid b{color:#d9efad;font-size:10px}.principle-grid h3{font:700 18px Manrope;margin:35px 0 10px}.principle-grid p{font-size:11px;line-height:1.7;color:#adbbb3}.reach{padding:105px 8vw;display:grid;grid-template-columns:1fr .8fr;gap:90px;align-items:center}.location-card{padding:32px;border:1px solid #dfe5de;border-radius:24px;background:#fff;box-shadow:var(--shadow)}.location-card span{font-size:8px;letter-spacing:.16em;color:#8a958d;font-weight:800}.location-card strong{display:block;font:800 25px Manrope;letter-spacing:-.04em;margin:17px 0 8px}.location-card small{display:block;color:#778178;font-size:10px;margin-bottom:24px}.location-card a{color:#4f6844;font-size:11px;font-weight:800;text-decoration:none}.about-cta{margin:0 8vw 100px;padding:45px 50px;border-radius:26px;background:#dcebc3;display:flex;align-items:center;justify-content:space-between;gap:30px}.about-cta h2{font-size:38px}@media(max-width:800px){.story-grid,.reach{grid-template-columns:1fr;gap:40px}.principle-grid{grid-template-columns:1fr 1fr}.principle-grid article:nth-child(2){border-right:0;margin:0}.reach{padding:75px 24px}.story{padding:75px 24px}.about-hero{padding:75px 24px}.principles{padding:75px 24px}.about-cta{margin:0 20px 70px;padding:32px;display:block}.about-cta .button{margin-top:25px}}@media(max-width:520px){.principle-grid{grid-template-columns:1fr}.principle-grid article{border-right:0;border-bottom:1px solid rgba(255,255,255,.13);margin:0;padding-bottom:25px}}
`]})
export class AboutComponent{}
